# initial parameter values
REFERNCE_FREQUENCY = 440
KEY = "c"
LEVEL = 0
NUMBER_OF_CYCLES = 15
SAMPLES_PER_CYCLE = 12.3

# some constants for the recoding buffer
BLOCK_SIZE = 512
NUM_FRAMES = 128

# plotting parameters
SAMPLE_RATE_FACTOR_FOR_SIGNAL_PLOT = 10
PLOT_REFRESH_TIME = 100 # ms

SIGNAL_PLOT_NUMBER_OF_CYCLES = 2

FOURIER_PLOT_DELTA_W_IN_PERCENT = 5
FOURIER_PLOT_NUMBER_OF_DATA_POINTS = 150

